### ISSUE TITLE
Writing a lot png images to seed file containing folder and trying to read them

### ISSUE THREAD

**Issue by mfbieber** [dedica-team/nivio#18]
When refreshing through the Browser on e.g. `http://localhost:8089/render/nivio:example/graph.png`, nivio tries to parse the other files contained in the directory:

<img width="687" alt="Screenshot 2019-08-11 at 13 46 25" src="https://user-images.githubusercontent.com/37021266/62833532-adb8a980-bc40-11e9-9d24-cf84882b6551.png">
<img width="1306" alt="Screenshot 2019-08-11 at 13 43 24" src="https://user-images.githubusercontent.com/37021266/62833533-adb8a980-bc40-11e9-80e8-99aefe82fc7f.png">
<img width="1137" alt="Screenshot 2019-08-11 at 13 43 14" src="https://user-images.githubusercontent.com/37021266/62833534-adb8a980-bc40-11e9-9f17-3d395ae11d00.png">

Maybe it should write them to a different directory or not try to parse them?

**Comment by mfbieber** [comment]
Because of this behaviour, it does not refresh anything, when I change any of the ymls.

**Comment by mfbieber** [comment]
My yml files were, base-configuration.yml
```
identifier: nivio:example
name: Landscape example
contact: mail@acme.org
sources:
  #- "./services/services.yml"
  - url: "./services/services.yml"
    format: nivio
  #- url: "http://some.server/docker-compose.yml"
    #format: docker-compose-v2
  #- url: https://gitlab.com/bonndan/nivio-private-demo/raw/docker-compose.yml
  # headerTokenName: PRIVATE_TOKEN
    #headerTokenValue: ${MY_SECRET_TOKEN_ENV_VAR}
```
and services.yml:
```
services:
  - identifier: blog-server
    short_name: blog1
    group: content

  - identifier: auth-gateway
    short_name: blog1
    layer: ingress
    group: content

  - identifier: DB1
    software: MariaDB
    version: 10.3.11
    type: database
    layer: infrastructure
    group: content
```
