### ISSUE TITLE
Enable nivio to collect, manage and display kpis

### ISSUE THREAD

**Issue by sl0815** [dedica-team/nivio#92]
In order to provide a high level architectural overview of the current application landscape it would be quite helpful if nivio also could collect, manage and display a set of kpis. Relevant kpis could be

- code coverage
- memory usage
- cpu load

In addition to just displaying those kpis, having some kind of alerting on top of them would be great (for example if code coverage drops below or memory usage rises above a defined treshold).

**Comment by bonndan** [comment]
Here is a suggestion to address collection of kpis:

* define KPIs in the config
* define ways to fetch data per KPI (e.g. scrape sonarqube html, read spring metrics json)
* provide placeholders (better name required) per item/service only, since most often sources only differ by an identifier

```yaml

identifier: nivio:kpi-collection
name: KPI collection

#
# landscape config
#
config:
  kpis:
    codecov:
      label: Code Coverage
      resolverTemplateUrl: https://sonarcloud.io/dashboard?id={{placeholder}}
      resolverTemplatePath: html("#overview-quality-gate-conditions-list > a > div > div.overview-quality-gate-condition-value > span")
    mem:
      label: Memory Usage
      resolverTemplateUrl: http://{{placeholder}}:8081/metrics
      resolverTemplatePath: jsonPath($.store)
    bugs:
      label: Open Bugs

#
# example items
#
items:
  - identifier: foo
    name: foo Service
    description: has kpis
    kpis:
      codecov:
        placeholder: simgrid_simgrid
      mem:
        placeholder: fooservice.local
      bugs:
        value: 1000

```

@sl0815 any comments?
