### ISSUE TITLE
Link code analysis artifacts

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#97]
"As an architect I want to drill down on landscape item details like code analysis artifacts".

Provide a means to assign links more easily than inserting them manually (one way is label parsing). E.g. configure a code analysis system like Sonarcube globally and map items to certain projects automatically. 

related to #92

**Comment by bonndan** [comment]
What about this approach, namely having links with special keys:

```yaml
items:
   - identifier: blog-server
     links:
       sonarqube: https://sonarcloud.io/dashboard?id=foo
```
The "sonarqube" key could be handled by some specialized SonarQube KPI resolver .
However, this would require a lot of copy/paste work and would hardly work with authentication. The approach mentioned in #92 would support authentication, since a preconfigured KPI resolver work work in a similar way as the resolvers fetching files from protected git repos.
